export const Products = [
  {
    id: 1,
    title: 'Quartz Black Dial Watch',
    description: "Grey stainless steel case and bracelet. Grey stainless steel bezel. Black dial with index hour markers. Dial Type: Analog. Luminescent hands and markers. Date display at the 4 o'clock position. Chronograph - three sub-dials displaying: 60 second, 60 minute and 1/10th of a second. Quartz movement. Scratch resistant sapphire crystal. Screw down crown. Solid case back. Round case shape, case size: 45.9mm, case thickness: 13.7. Water resistant at 200 meters / 660 feet. Watch label: Japan Movt.",
    brand: 'Citizen',
    rating: 4,
    reviews: 5,
    price: 300,
    discount: 25,
    warranty: 1,
    sku: 'CB5007-51H',
    gender: 'male',
    stock: 6,
    imgUrl: ["/watch1/img1.jpg"]
  },
  {
    id: 2,
    title: 'Classic Leather Strap Watch',
    description: "Brown leather strap with stainless steel case. White dial with Roman numeral hour markers. Analog display with date window. Quartz movement. Scratch-resistant mineral crystal. Case size: 42mm, case thickness: 11mm. Water resistant at 50 meters / 165 feet.",
    brand: 'Seiko',
    rating: 4.5,
    reviews: 8,
    price: 150,
    discount: 15,
    warranty: 2,
    sku: 'SKL1023',
    gender: 'male',
    stock: 10,
    imgUrl: ["/watch2/img1.jpg"]
  },
  {
    id: 3,
    title: 'Minimalist Rose Gold Watch',
    description: "Rose gold stainless steel case with mesh bracelet. Black dial with minimalist hour markers. Quartz movement. Scratch-resistant sapphire crystal. Case size: 40mm, case thickness: 7mm. Water resistant at 30 meters / 100 feet.",
    brand: 'Daniel Wellington',
    rating: 4.8,
    reviews: 20,
    price: 200,
    discount: 10,
    warranty: 1,
    sku: 'DW5010RG',
    gender: 'female',
    stock: 15,
    imgUrl: ["/watch3/img1.jpg"]
  },
  {
    id: 4,
    title: 'Sports Chronograph Watch',
    description: "Black rubber strap with stainless steel case. Blue dial with luminescent hands and markers. Chronograph functionality with three sub-dials. Quartz movement. Scratch-resistant mineral crystal. Case size: 46mm, case thickness: 14mm. Water resistant at 100 meters / 330 feet.",
    brand: 'Casio',
    rating: 4.2,
    reviews: 12,
    price: 120,
    discount: 20,
    warranty: 1,
    sku: 'CA1001B',
    gender: 'male',
    stock: 8,
    imgUrl: ["/watch4/img1.jpg"]
  },
  {
    id: 5,
    title: 'Gold-Plated Luxury Watch',
    description: "Gold-plated stainless steel case and bracelet. White dial with gold-tone markers. Analog display with date window. Automatic movement. Sapphire crystal. Case size: 43mm, case thickness: 12mm. Water resistant at 100 meters / 330 feet.",
    brand: 'Tissot',
    rating: 4.7,
    reviews: 18,
    price: 400,
    discount: 30,
    warranty: 3,
    sku: 'TISLX103',
    gender: 'male',
    stock: 5,
    imgUrl: ["/watch5/img1.jpg"]
  },
  {
    id: 6,
    title: 'Vintage Silver Watch',
    description: "Silver-tone stainless steel case and bracelet. Black dial with stick hour markers. Quartz movement. Mineral crystal. Case size: 39mm, case thickness: 9mm. Water resistant at 30 meters / 100 feet.",
    brand: 'Fossil',
    rating: 4.3,
    reviews: 9,
    price: 100,
    discount: 10,
    warranty: 1,
    sku: 'FS1009SL',
    gender: 'unisex',
    stock: 20,
    imgUrl: ["/watch6/img1.jpg"]
  },
  {
    id: 7,
    title: 'Smartwatch with Fitness Tracker',
    description: "Rubber strap with digital display. Tracks heart rate, steps, and sleep patterns. Bluetooth connectivity for smartphone syncing. Water resistant at 50 meters / 165 feet. Case size: 45mm, case thickness: 11mm.",
    brand: 'Garmin',
    rating: 4.6,
    reviews: 25,
    price: 250,
    discount: 20,
    warranty: 2,
    sku: 'GRMN1005',
    gender: 'unisex',
    stock: 12,
    imgUrl: ["/watch7/img1.jpg"]
  },
  {
    id: 8,
    title: 'Elegant Ceramic Watch',
    description: "White ceramic case and bracelet. Rose gold-tone accents. Analog display with date window. Quartz movement. Sapphire crystal. Case size: 38mm, case thickness: 10mm. Water resistant at 30 meters / 100 feet.",
    brand: 'Rado',
    rating: 4.9,
    reviews: 30,
    price: 600,
    discount: 25,
    warranty: 3,
    sku: 'RAD1025C',
    gender: 'female',
    stock: 7,
    imgUrl: ["/watch8/img1.jpg"]
  },
  {
    id: 9,
    title: 'Digital Outdoor Watch',
    description: "Black resin case and strap. Digital display with multiple features like stopwatch, countdown timer, and alarm. Water resistant at 200 meters / 660 feet. Case size: 48mm, case thickness: 15mm.",
    brand: 'Timex',
    rating: 4.4,
    reviews: 16,
    price: 90,
    discount: 5,
    warranty: 1,
    sku: 'TX1007D',
    gender: 'male',
    stock: 25,
    imgUrl: ["/watch9/img1.jpg"]
  },
  {
    id: 10,
    title: 'Luxury Diamond Watch',
    description: "18k gold case and bracelet with diamond accents. Mother-of-pearl dial with diamond hour markers. Analog display. Quartz movement. Sapphire crystal. Case size: 36mm, case thickness: 9mm. Water resistant at 50 meters / 165 feet.",
    brand: 'Omega',
    rating: 5,
    reviews: 10,
    price: 5000,
    discount: 15,
    warranty: 5,
    sku: 'OMX1001D',
    gender: 'female',
    stock: 3,
    imgUrl: ["/watch10/img1.jpg"]
  }
];
