import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google"
import { ArrowUp } from "lucide-react";
import { Button } from "@/components/ui/button";


const lato = Lato({
  weight: ["400", "300","700", "900"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-lato"
})


export const metadata: Metadata = {
  title: "Watch And Whimsy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${lato.variable} ${lato.className}`}>
        {children}
        <Button variant='bgGreen' className='md:fixed hidden md:block bottom-2 right-2'>
          <ArrowUp />
        </Button>
      </body>
    </html>
  );
}