import type { Metadata } from 'next'
import './globals.css'
import { Lato, League_Spartan } from 'next/font/google'

const lato = Lato({
  weight: ['400', '300', '700', '900'],
  subsets: ['latin', 'latin-ext'],
  variable: '--font-lato'
})
const spartan = League_Spartan({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin', 'latin-ext'],
  variable: '--font-spartan'
})

export const metadata: Metadata = {
  title: 'Watch And Whimsy',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${lato.variable} ${spartan.variable} ${lato.className}`}
      >
        {children}
      </body>
    </html>
  )
}
